# Generated by Django 3.2.20 on 2023-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_content_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/img_1.jpg', upload_to='blog'),
        ),
    ]
